main: me.sothatsit.mobeggspawnerblocker.MobEggSpawnerBlocker
authors: [sothatsit,nayoshi12]
name: MobEggSpawnerBlocker
version: 1.2.1
api-version: 1.13
commands:
   mobeggspawnerblocker:
      description: 'reload MobEggSpawnerBlocker config'
permissions:
   mobeggspawnerblocker.reload:
      description: 'gives access to /mobeggspawnerblocker command'
      default: op
   mobeggspawnerblocker.override:
      description: 'Override mob egg spawner blocker'
      default: op